schoolmanager/schoolapi/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers, viewsets
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

router = routers.DefaultRouter()
router.register('users', views.UserView)
# router.register('students', views.StudentView)
# router.register('instructors', views.InstructorView)
router.register('class', views.ClassView)
router.register('clubs', views.ClubView)
router.register('events', views.EventView)
router.register('exam', views.ExamView)
router.register('homework', views.HomeworkView)
router.register('assignment', views.AssignmentView)
router.register('exam_prep', views.ExamPrepView)
router.register('finance', views.FinanceView)

urlpatterns = [
    path('api/', include(router.urls), name='api'),
    path('', views.dashboard),
    path('finances/', views.finances),
    path('tasks/', views.tasks),
    path('clubsEvents/', views.clubsEvents),

    path('add-class/', views.addClass),
    path('delete-class/<id>', views.deleteClass, name='delete-class'),
    path('update-class/<id>', views.updateClass, name='update-class'),

    path('add-club/', views.addClub),
    path('delete-club/<id>', views.deleteClub, name='delete-club'),
    path('update-club/<id>', views.updateClub, name='update-club'),

    path('add-event/', views.addEvent),
    path('delete-event/<id>', views.deleteEvent, name='delete-event'),
    path('update-event/<id>', views.updateEvent, name='update-event'),

    path('add-exam/', views.addExam),
    path('delete-exam/<id>', views.deleteExam, name='delete-exam'),
    path('update-exam/<id>', views.updateExam, name='update-exam'),
    
    path('add-homework/', views.addHomework),
    path('delete-homework/<id>', views.deleteHomework, name='delete-homework'),
    path('update-homework/<id>', views.updateHomework, name='update-homework'),

    path('add-assignment/', views.addAssignment),
    path('delete-assignment/<id>', views.deleteAssignment, name='delete-assignment'),
    path('update-assignment/<id>', views.updateAssignment, name='update-assignment'),

    path('add-exam-prep/', views.addExamPrep),
    path('delete-exam-prep/<id>', views.deleteExamPrep, name='delete-exam-prep'),
    path('update-exam-prep/<id>', views.updateExamPrep, name='update-exam-prep'),

    path('add-finance/', views.addFinance),
    path('delete-finance/<id>', views.deleteFinance, name='delete-finance'),
    path('update-income/<id>', views.updateFinancePos, name='update-income'),
    path('update-costs/<id>', views.updateFinanceNeg, name='update-costs')
]

schoolmanager/schoolmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    #include adds urls from schoolapi.urls to this file
    #to increase readability
    path('', include('schoolapi.urls')),
    path('register/', v.register, name='register'),
    path('', include("django.contrib.auth.urls")),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catalog'),
    path('logout/', v.logout, name='logout'),
]

schoolmanager/schoolapi/models.py
from django.db import models
from django.db.models.fields import CharField
from django.contrib.auth.models import User, UserManager, AbstractUser
from django.contrib.auth import get_user_model
User = get_user_model()
from register.models import CustomUser

# Create your models here.
TYPE_CHOICES = [
    ('Network', 'Networking'),
    ('InfoSess', 'Information Session'),
    ('Speaker', 'Career Fair'),
    ('Party', 'Party'),
    ('Workshop', 'Workshop'),
    ('Sports', 'Sports'),
    ('Conference', 'Conference'),
    ('Other', 'Other'),
] 

#class User (models.Model):
#    username = models.CharField(max_length=50)
#    school = models.CharField(max_length=50)

#    def __str__(self):
#        return '%s' % (self.username)

#    class Meta:
#        abstract = True

class Class(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    time = models.TimeField(max_length=50)
    section = models.CharField(max_length=50)
    room = models.CharField(max_length=50, blank=True)


    def __str__(self):
        return '%s' % (self.name)

class Club(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    meeting_time = models.TimeField(max_length=50, blank=True)

    def __str__(self):
        return '%s' % (self.name)

   
class Event(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    date = models.DateField(max_length=50)
    description = models.CharField(max_length = 1000, blank=True)
    host = models.CharField(max_length=50, blank=True)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    
PRIORITY_CHOICES = [
    ('High', 'High'),
    ('Medium', 'Medium'),
    ('Low', 'Low')
]
class Task(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    className = models.ForeignKey(Class, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=50)
    date = models.DateField()
    description = models.CharField(max_length=1000, blank=True)
    priority = models.CharField(max_length=50, choices=PRIORITY_CHOICES)

    class Meta:
        abstract=True

    def __str__(self):
        return self.task_name

class Exam(Task):
    start_time = models.TimeField(max_length=50)
    room = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % (self.task_name)

class Homework(Task):
    no_questions = models.IntegerField(blank=True)

    def __str__(self):
        return '%s' % (self.task_name)

class Assignment(Task):
    group_members = models.CharField(max_length = 1000, blank = True)
    module = models.CharField(max_length = 50, blank = True)

class ExamPrep(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    PREP_CHOICES = [
        ('Practice Exam', 'Practice Exam'),
        ('Review Session', 'Review Session'),
        ('Exam Prep Event', 'Exam Prep Event'),
        ('Other', 'Other')
    ]
    prep_type = models.CharField(max_length = 100, choices = PREP_CHOICES)
    
class Finance(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    initialBudget = models.FloatField()
    income = models.FloatField()
    tuition = models.FloatField()
    equipment = models.FloatField()
    books = models.FloatField()

    @property
    def total(self):
        return self.initialBudget + self.income - self.tuition - self.equipment - self.books

    #student = models.OneToOneField(Student, on_delete=models.CASCADE)

# class customUser(AbstractUser):
#     acc_types = (
#         ('Student', 'Student'),
#         ('Instructor', 'Instructor')
#     )
#     user_type = models.CharField(max_length=2,
#                                  choices=acc_types)

# class UserDetails(models.Model):
#     type = models.OneToOneField('CustomUser', on_delete=models.CASCADE)
#     extra_info = models.CharField(max_length=200)

schoolmanager/schoolapi/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .models import *
from .serializers import *
import requests
from .forms import *
from django.http import HttpResponseRedirect
from django.db.models import Sum
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

# API
class UserView(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# class StudentView(viewsets.ModelViewSet):
#     queryset = Student.objects.all()
#     serializer_class = StudentSerializer

# class InstructorView(viewsets.ModelViewSet):
#     queryset = Instructor.objects.all()
#     serializer_class = InstructorSerializer
    
class ClassView(viewsets.ModelViewSet):
    queryset = Class.objects.all()
    serializer_class = ClassSerializer

class ClubView(viewsets.ModelViewSet):
    queryset = Club.objects.all()
    serializer_class = ClubSerializer

class EventView(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer

class ExamView(viewsets.ModelViewSet):
    queryset = Exam.objects.all()
    serializer_class = ExamSerializer

class HomeworkView(viewsets.ModelViewSet):
    queryset = Homework.objects.all()
    serializer_class = HomeworkSerializer

class AssignmentView(viewsets.ModelViewSet):
    queryset = Assignment.objects.all()
    serializer_class = AssignmentSerializer

class ExamPrepView(viewsets.ModelViewSet):
    queryset = ExamPrep.objects.all()
    serializer_class = ExamPrepSerializer

class FinanceView(viewsets.ModelViewSet):
    queryset = Finance.objects.all()
    serializer_class = FinanceSerializer

# FRONT END
def dashboard(request):
    # response = requests.get('http://'+request.get_host()+'/api/class/')
    # classes = response.json()

    # response = requests.get('http://'+request.get_host()+'/api/exam/')
    # exams = response.json()

    # response = requests.get('http://'+request.get_host()+'/api/homework/')
    # homework = response.json()

    # response = requests.get('http://'+request.get_host()+'/api/assignment/')
    # assignments = response.json()

    # response = requests.get('http://'+request.get_host()+'/api/clubs/')
    # clubs = response.json()

    # response = requests.get('http://'+request.get_host()+'/api/events/')
    # events = response.json()

    # response = requests.get('http://'+request.get_host()+'/api/exam_prep/')
    # exam_prep = response.json()

    # response = requests.get('http://'+request.get_host()+'/api/finance/')
    # finance = response.json()
    if request.user.is_authenticated:
        classes = Class.objects.all()
        if request.user.is_student:
            return render(request, "schoolapi/dashboard.html", {'classes': classes})
        if request.user.is_instructor:
            return render(request, "schoolapi/dashboard_instructor.html", {'classes': classes})
        return render(request, "schoolapi/dashboard.html", {'classes': classes})
    return HttpResponseRedirect("/login")
    #{"classes" : classes, 
    #"exams" : exams, "homework" : homework, "assignments" : assignments, "clubs" : clubs,
    #"events" : events, "exam_prep" : exam_prep, "finance" : finance}

def finances(request):
    if request.user.is_authenticated:
        finance = Finance.objects.all()
        return render(request, "schoolapi/finances.html", {'finance': finance})
    return HttpResponseRedirect("/login")

def tasks(request):
    if request.user.is_authenticated:
        if request.user.is_student:
            exams = Exam.objects.all()
            exam_prep = ExamPrep.objects.all()
            homework = Homework.objects.all()
            assignments = Assignment.objects.all()
            return render(request, "schoolapi/tasks.html", {'exams': exams, 'exam_prep': exam_prep,
            'homework': homework, 'assignments': assignments})
        if request.user.is_instructor:
            exams = Exam.objects.all()
            exam_prep = ExamPrep.objects.all()
            homework = Homework.objects.all()
            assignments = Assignment.objects.all()
            return render(request, "schoolapi/tasks_instructor.html", {'exams': exams, 'exam_prep': exam_prep,
            'homework': homework, 'assignments': assignments})
    return HttpResponseRedirect("/login")

def clubsEvents(request):
    if request.user.is_authenticated:
        clubs = Club.objects.all()
        events = Event.objects.all()
        return render(request, "schoolapi/clubsEvents.html", {'clubs': clubs, 'events': events})
    return HttpResponseRedirect("/login")

##### Class CRUD #####
def addClass(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ClassForm(request.POST)
            if form.is_valid():
                request.user.class_set.create(
                    name=form.cleaned_data["name"],
                    time=form.cleaned_data["time"],
                    section=form.cleaned_data["section"],
                    room=form.cleaned_data["room"]

                    )
                #form.save()
                return HttpResponseRedirect("/")
                
        else:
            form = ClassForm()
        return render(request, 'schoolapi/forms.html', {'form': form})
    return HttpResponseRedirect("/login")

def deleteClass(request, id):
    if request.user.is_authenticated:
        class_data = Class.objects.get(id=id)
        if request.method == 'POST':
            class_data.delete()
            return HttpResponseRedirect("/")
        return render(request, "schoolapi/delete_view.html", {"data": class_data})
    return HttpResponseRedirect("/login")

def updateClass(request, id):
    if request.user.is_authenticated:
        class_data = Class.objects.get(id=id)
        form = ClassForm(instance=class_data)
        if request.method == 'POST':
            form = ClassForm(request.POST, instance=class_data)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect("/")
                
        return render(request, 'schoolapi/forms.html', {'form': form})
    return HttpResponseRedirect("/login")

##### Club CRUD #####
def addClub(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ClubForm(request.POST)
            if form.is_valid():
                request.user.club_set.create(
                    name=form.cleaned_data["name"],
                    meeting_time=form.cleaned_data["meeting_time"],
                )
                return HttpResponseRedirect("/clubsEvents")
        else:
            form = ClubForm()
                
        return render(request, 'schoolapi/forms.html', {'form': form})
    return HttpResponseRedirect("/login")

def deleteClub(request, id):
    if request.user.is_authenticated:
        club_data = Club.objects.get(id=id)
        if request.method == 'POST':
            club_data.delete()
            return HttpResponseRedirect("/clubsEvents")
        return render(request, "schoolapi/delete_view.html", {"data": club_data})
    return HttpResponseRedirect("/login")

def updateClub(request, id):
    if request.user.is_authenticated:
        club_data = Club.objects.get(id=id)
        form = ClubForm(instance=club_data)
        if request.method == 'POST':
            form = ClubForm(request.POST, instance=club_data)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect("/clubsEvents")
                
        return render(request, 'schoolapi/forms.html', {'form': form})
    return HttpResponseRedirect("/login")

##### Event CRUD #####
def addEvent(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = EventForm(request.POST, user=request.user)
            if form.is_valid():
                request.user.event_set.create(
                    name=form.cleaned_data["name"],
                    date=form.cleaned_data["date"],
                    description=form.cleaned_data["description"],
                    host=form.cleaned_data["host"],
                    type=form.cleaned_data["type"],
                    club=form.cleaned_data["club"],
                )
                return HttpResponseRedirect("/clubsEvents")
                
        else:
            form = EventForm(user=request.user)
                
        return render(request, 'schoolapi/forms.html', {'form': form})
    return HttpResponseRedirect("/login")

def deleteEvent(request, id):
    if request.user.is_authenticated:
        event_data = Event.objects.get(id=id)
        if request.method == 'POST':
            event_data.delete()
            return HttpResponseRedirect("/clubsEvents")
        return render(request, "schoolapi/delete_view.html", {"data": event_data})
    return HttpResponseRedirect("/login")

def updateEvent(request, id):
    if request.user.is_authenticated:
        event_data = Event.objects.get(id=id)
        form = EventForm(instance=event_data, user=request.user)
        if request.method == 'POST':
            form = EventForm(request.POST, instance = event_data, user=request.user)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect("/clubsEvents")
                
        return render(request, 'schoolapi/forms.html', {'form': form})
    return HttpResponseRedirect("/login")
    
##### Exam CRUD #####
def addExam(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ExamForm(request.POST, user=request.user)
            if form.is_valid():
                request.user.exam_set.create(
                className=form.cleaned_data["className"],
                task_name=form.cleaned_data["task_name"],
                date=form.cleaned_data["date"],
                description=form.cleaned_data["description"],

schoolmanager/templates/schoolapi/finances.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous" />

    <title>Finance</title>
    <link rel="stylesheet" href="{% static 'schoolapi/css/style.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
</head>
<body>
    <div class="top-nav-container">
        <div class="wrapper">
            <nav role="main">
                <div class="title">
                    Finance
                </div>

                <div class="logo">
                    <img src="{% static 'schoolapi/images/logos.png' %}" alt="My image">
                </div>

                <div class="username">
                    {{user.get_username}}
                </div>

                <div class="logout" href="/login">
                    <a href="{% url 'logout' %}">Logout</a>
                </div>

            </nav>
        </div>

    </div>

    <div class="side-nav-container" style="height: 100%;">

        <div class="sidebar" style="top: 150px;">
        </div>

        <div class="wrapper">
            <nav id="menubar">
                <ul class="nav-items">
                    <li>
                        <a href="/">Dashboard</a>
                    </li>
                    <li>
                        <a href="/tasks">Tasks</a>
                    </li>
                    <li>
                        <a href="/clubsEvents">Clubs & Events</a>
                    </li>
                    <li>
                        <a href="/finances">Finance</a>
                    </li>
                </ul>

            </nav>
        </div>

    </div>

    <div class="finances-container">
        <div class="item-title">
            Finance
        </div>
        <button type="button" onclick="window.location.href='/add-finance'" class="btn-add-item" id="add">
            <img src="{% static 'schoolapi/images/add.png' %}">
        </button>
        <!-- <button type="button" onclick="window.location.href='/add-finance'" class="btn-add-item" style="margin-left: 50px;">
            <img src="{% static 'schoolapi/images/sub.png' %}">
        </button> -->
        {% for f in user.finance_set.all%}
        <script>
            document.getElementById("add").style.display = "none";
        </script>
        <div class="item-attributes">
            <div class="item-background">
            </div>
            <ul class="show-items">
                <div id="name">
                    ${{f.initialBudget|floatformat:2}}
                </div>
                <table>
                    <tr>
                        <td>Income</td>
                        <td>+${{f.income|floatformat:2}}</td>
                    </tr>
                    <tr>
                        <td>Tuition</td>
                        <td>-${{f.tuition|floatformat:2}}</td>
                    </tr>
                    <tr>
                        <td style="padding-right: 20px;">Equipment</td>
                        <td>-${{f.equipment|floatformat:2}}</td>
                    </tr>
                    <tr>
                        <td>Books</td>
                        <td>-${{f.books|floatformat:2}}</td>
                    </tr>
                </table>
                <div id="name" style="margin-bottom: -30px;">
                    Total: ${{f.total|floatformat:2}}
                </div>
                <li id="btn-delete-item" style="margin-left: 150px; margin-right: 20px;">
                    <a href="{% url 'delete-finance' f.id%}">
                        <img src="{% static 'schoolapi/images/Delete.png' %}">
                    </a>
                </li>
            </ul>
            <a href="{% url 'update-income' f.id%}" class="btn-add-item">
                <img src="{% static 'schoolapi/images/add.png' %}">
            </a>
            <a href="{% url 'update-costs' f.id%}" class="btn-add-item" style="margin-left: 50px;">
                <img src="{% static 'schoolapi/images/sub.png' %}">
            </a>
        </div>
        {% endfor %}
    </div>
</body>
</html>

schoolmanager/templates/schoolapi/tasks.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous" />

    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'schoolapi/css/style.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
</head>
<style>
    .row {
    width: 100%;
    margin: 0 auto;
    }
    .block {
    width: 300px;
    display: inline-block
    }
</style>
<body>
    <div class="top-nav-container">
        <div class="wrapper">
            <nav role="main">
                <div class="title">
                    Tasks
                </div>

                <div class="logo">
                    <img src="{% static 'schoolapi/images/logos.png' %}" alt="My image">
                </div>

                <div class="username">
                    {{user.get_username}}
                </div>

                <div class="logout" href="/login">
                    <a href="{% url 'logout' %}">Logout</a>
                </div>

            </nav>
        </div>

    </div>

    <div class="side-nav-container" style="height: 170%;">
        <div class="sidebar" style="top: 50px;">
        </div>
        <div class="wrapper">
            <nav id="menubar">
                <ul class="nav-items">
                    <li>
                        <a href="/">Dashboard</a>
                    </li>
                    <li>
                        <a href="/tasks">Tasks</a>
                    </li>
                    <li>
                        <a href="/clubsEvents">Clubs & Events</a>
                    </li>
                    <li>
                        <a href="/finances">Finance</a>
                    </li>
                </ul>

            </nav>
        </div>
    </div>

    <div class="exams-container row">
        <div class="item-title">
            Exams
        </div>
        <button type="button" onclick="window.location.href='/add-exam'" class="btn-add-item" style="left: 330px;">
            <img src="{% static 'schoolapi/images/add.png' %}">
        </button>
        {% for exam in user.exam_set.all %}
        <div class="item-attributes block">
            <div class="item-background">
            </div>
            <ul class="show-items" style="position: absolute;">
                <li id="name">
                    {{exam.task_name}}
                </li>
                <li>
                    Class: {{exam.className}}
                </li>
                <li>
                    Date: {{exam.date}}
                </li>
                <li style="overflow: auto;">
                    Description: {{exam.description}}
                </li>
                <li>
                    Start Time: {{exam.start_time}}
                </li>
                <li>
                    Room: {{exam.room}}
                </li>

                <li id="btn-update-item">
                    <a href="{% url 'update-exam' exam.id%}">
                        <img src="{% static 'schoolapi/images/edit.png' %}">
                    </a>
                </li>

                <li id="btn-delete-item">
                    <a href="{% url 'delete-exam' exam.id%}">
                        <img src="{% static 'schoolapi/images/Delete.png' %}">
                    </a>
                </li>
            </ul>
        </div>
        {% endfor %}
    </div>
    <div class="exam_prep-container row">
        <div class="item-title" style="margin-top: 390px">
            Exam Prep
        </div>
        <button type="button" onclick="window.location.href='/add-exam-prep'" class="btn-add-item" style="margin-top: 390px; margin-left: 50px;">
            <img src="{% static 'schoolapi/images/add.png' %}">
        </button>
        {% for e in user.examprep_set.all %}
        <div class="item-attributes block">
            <div class="item-background">
            </div>
            <ul class="show-items" style="position: absolute; margin-top: 490px;">
                <li id="name">
                    {{e.exam}}
                </li>
                <li>
                    Prep Type: {{e.prep_type}}
                </li>


                <li id="btn-update-item">
                    <a href="{% url 'update-exam-prep' e.id%}">
                        <img src="{% static 'schoolapi/images/edit.png' %}">
                    </a>
                </li>

                <li id="btn-delete-item">
                    <a href="{% url 'delete-exam-prep' e.id%}">
                        <img src="{% static 'schoolapi/images/Delete.png' %}">
                    </a>
                </li>

            </ul>

        </div>
        {% endfor %}
    </div>

    <div class="homework-container row">
        <div class="item-title" style="margin-top: 730px">
            Homework
        </div>
        <button type="button" onclick="window.location.href='/add-homework'" class="btn-add-item" style="margin-top: 730px; margin-left: 50px;">
            <img src="{% static 'schoolapi/images/add.png' %}">
        </button>
        {% for hw in user.homework_set.all %}
        <div class="item-attributes block">
            <div class="item-background">
            </div>
            <ul class="show-items" style="position: absolute; margin-top: 830px;">
                <li id="name">
                    {{hw.task_name}}
                </li>
                <li>
                    Class: {{hw.className}}
                </li>
                <li>
                    Date: {{hw.date}}
                </li>
                <li style="overflow: auto;">
                    Description: {{hw.description}}
                </li>
                <li>
                    Priority: {{hw.priority}}
                </li>
                <li>
                    No Questions: {{hw.no_questions}}
                </li>

                <li id="btn-update-item">
                    <a href="{% url 'update-homework' hw.id%}">
                        <img src="{% static 'schoolapi/images/edit.png' %}">
                    </a>
                </li>

                <li id="btn-delete-item">
                    <a href="{% url 'delete-homework' hw.id%}">
                        <img src="{% static 'schoolapi/images/Delete.png' %}">
                    </a>
                </li>

            </ul>

        </div>
        {% endfor %}
    </div>

    <div class="assignment-container row">
        <div class="item-title" style="margin-top: 1120px">
            Assignment
        </div>
        <button type="button" onclick="window.location.href='/add-assignment'" class="btn-add-item" style="margin-top: 1120px; margin-left: 70px;">
            <img src="{% static 'schoolapi/images/add.png' %}">
        </button>
        {% for assignment in user.assignment_set.all %}
        <div class="item-attributes block">
            <div class="item-background">
            </div>
            <ul class="show-items" style="position: absolute; margin-top: 1220px;">
                <li id="name">
                    {{assignment.task_name}}
                </li>
                <li>
                    Class: {{assignment.className}}
                </li>
                <li>
                    Date: {{assignment.date}}
                </li>
                <li style="overflow: auto;">
                    Description: {{assignment.description}}
                </li>
                <li>
                    Priority: {{assignment.priority}}
                </li>
                <li style="overflow: auto;">
                    Group Members: {{assignment.group_members}}
                </li>
                <li style="overflow: auto;">
                    Module: {{assignment.module}}
                </li>

                <li id="btn-update-item">
                    <a href="{% url 'update-assignment' assignment.id%}">
                        <img src="{% static 'schoolapi/images/edit.png' %}">
                    </a>
                </li>

                <li id="btn-delete-item">
                    <a href="{% url 'delete-assignment' assignment.id%}">
                        <img src="{% static 'schoolapi/images/Delete.png' %}">
                    </a>
                </li>

            </ul>

        </div>
        {% endfor %}
    </div>

</body>
</html>